name: Build/release

on: push

jobs:
  release-linux:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: rpm
        run: |
          sudo apt update 1>&2
          sudo apt install --install-recommends rpm -y 1>&2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
          github_token: ${{ secrets.github_token }}

      - run: yarn install --network-timeout 100000
      - run: yarn run build

  release-macos:
    runs-on: macos-latest
    environment: release
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
          github_token: ${{ secrets.github_token }}

      - run: yarn install --network-timeout 100000
      - run: yarn run build

  release-windows:
    runs-on: windows-latest
    environment: release
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
          github_token: ${{ secrets.github_token }}

      - run: yarn install --network-timeout 100000
      - run: yarn run build